// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKhHSHg6e-3lmjeyZ022lxv9GnWhZ74Ko',
    appId: '1:603054061781:web:8302378bdf496af47bca5c',
    messagingSenderId: '603054061781',
    projectId: 'talksy-a92b2',
    authDomain: 'talksy-a92b2.firebaseapp.com',
    storageBucket: 'talksy-a92b2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVRJm4xDJfTPOy2umHi_entiC-ztgTcak',
    appId: '1:603054061781:android:193c034e181a38a77bca5c',
    messagingSenderId: '603054061781',
    projectId: 'talksy-a92b2',
    storageBucket: 'talksy-a92b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNleKwKGv6FUTlLcDM-ma9tkjO2q8GtV0',
    appId: '1:603054061781:ios:ab06a5f6138d87a87bca5c',
    messagingSenderId: '603054061781',
    projectId: 'talksy-a92b2',
    storageBucket: 'talksy-a92b2.firebasestorage.app',
    iosBundleId: 'com.example.talksy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNleKwKGv6FUTlLcDM-ma9tkjO2q8GtV0',
    appId: '1:603054061781:ios:ab06a5f6138d87a87bca5c',
    messagingSenderId: '603054061781',
    projectId: 'talksy-a92b2',
    storageBucket: 'talksy-a92b2.firebasestorage.app',
    iosBundleId: 'com.example.talksy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKhHSHg6e-3lmjeyZ022lxv9GnWhZ74Ko',
    appId: '1:603054061781:web:f64b465c6d0b3f387bca5c',
    messagingSenderId: '603054061781',
    projectId: 'talksy-a92b2',
    authDomain: 'talksy-a92b2.firebaseapp.com',
    storageBucket: 'talksy-a92b2.firebasestorage.app',
  );
}
